# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
# set for rss
name: 子孑
description: What is a Career in Big Data?
url: http://zhangjunhd.github.io

markdown:       rdiscount
safe:           true
lsi:            false
pygments:       true
paginate:       10
permalink:      /:year/:month/:day/:title.html
title:          子孑
feed:           /atom.xml
author:
    name:       Holbrook
    twitter:    twitter.com/holbrook
author_info:    <a href="http://zhangjunhd.github.io/about.html">Zhang Jun</a>
category_code:
    - 量化金融:  quant    
    - 解决方案:  solution 
    - tools:    工具使用
    - develop:  软件开发
    - domain:   领域模型
    - methods:  手段方法
    - reading:  读书笔记
    - others:   杂七杂八
menuitems:
    - name:     首页
      url:      /index.html
    - name:     分类
      url:      /pages/categories.html
    - name:     标签
      url:      /pages/tags.html
    - name:     归档
      url:      /pages/archive.html